spring:
  application:
    name: pacelist
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            scope: user-read-email,playlist-modify-public,playlist-modify-private,user-read-recently-played,user-library-read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: __session
app:
  current-domain: ${CURRENT_DOMAIN:localhost}

