name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      - 'gh-actions-test'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: 'europe-west1'  # Ensure this matches both Cloud Run and Artifact Registry region
  SERVICE: 'my-service'
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    environment: 'production'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # Debug: Check the token to ensure it's being passed correctly
      - name: 'Debug Authentication Token'
        run: |-
          echo 'Auth Token: ${{ steps.auth.outputs.auth_token }}'

      # Docker login
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # Build and push Docker container to Artifact Registry
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" ./backend
          docker push "${DOCKER_TAG}"

      # Deploy to Cloud Run
      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      # Show Cloud Run URL (optional)
      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
