name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      - 'gh-actions-test'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: 'europe-west1'
  SERVICE: 'pacelist-app-back'
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  LOGIN_REDIRECT_URL: ${{ secrets.LOGIN_REDIRECT_URL }}

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    environment: 'production'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using the Service Account key
      - name: 'Set up Google Cloud credentials'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Generate an access token for Docker authentication
      - id: 'auth'
        name: 'Generate Access Token'
        run: |
          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      # Docker login
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # Build and push Docker container to Artifact Registry
      - name: 'Build and Push Container'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-service/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" ./backend
          docker push "${DOCKER_TAG}"

      # Deploy the container to Cloud Run
      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-service/${{ env.SERVICE }}:${{ github.sha }}'
          # Specify environment variables here
          env_vars: |
            SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
            ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            LOGIN_REDIRECT_URL=${{ secrets.LOGIN_REDIRECT_URL }}

      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
