name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      - 'gh-actions-test'  # Added new trigger branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: 'europe-west1'  # Unified region for both Artifact Registry and Cloud Run
  SERVICE: 'my-service'  # Update to your service name
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    environment: 'production'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using the Service Account key
      - name: 'Set up Google Cloud credentials'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Generate an access token for Docker authentication
      - id: 'auth'
        name: 'Generate Access Token'
        run: |
          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      # Docker login
      - name: 'Docker Auth'
        uses: 'docker/login-action
